---
#
# file: tasks/install-prometheus.yml
#

- name: download and untar Prometheus tarball
  unarchive:
    src: "{{ prometheus_tarball }}"
    dest: "{{ prometheus_install_path }}"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  tags:
    - tar

- name: create Prometheus server directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - "{{ prometheus_config_path }}"
    - "{{ prometheus_db_path }}"
    - "{{ prometheus_rule_path }}"

- name: copy Prometheus main config file
  template:
    src: "{{ prometheus_config }}"
    dest: "{{ prometheus_config_path }}/prometheus.yml"

- name: copy Prometheus rules file
  copy:
    src: "{{ prometheus_rule }}"
    dest: "{{ prometheus_rule_path }}/"

- name: copy Prometheus systemd config to server
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: "a+x"
